// gdg-blog-sveltekit/src/components/Navbar.svelte
<div class="px-4 py-5 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
    <div class="ml-2 tracking-wide flex justify-between">
      <div class="font-bold text-xl text-blue-700">
        <a href="/">GDG Blog</a>
      </div>
      <a href="/about">About Us</a>
    </div>
  </div>

// gdg-blog-nuxt/components/Navbar.vue
<template>
    <div class="px-4 py-5 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
        <div class="ml-2 tracking-wide flex justify-between">
            <div class="font-bold text-xl text-blue-700">
                <a href="/">GDG Blog</a>
            </div>
            <a href="/about">About Us</a>
        </div>
    </div>
</template>
