// gdg-blog-gatsby/src/components/Navbar.jsx
import React from "react";
import { Link } from "gatsby";

const Navbar = () => {
  return (
    <div className="px-4 py-5 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
      <div className="ml-2 tracking-wide flex justify-between">
        <div className="font-bold text-xl text-blue-700">
          <Link to="/">GDG Blog</Link>
        </div>
        <Link to="/about">About Us</Link>
      </div>
    </div>
  );
};

export default Navbar;

// gdg-blog-nuxt/components/Navbar.vue
<template>
    <div class="px-4 py-5 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
        <div class="ml-2 tracking-wide flex justify-between">
            <div class="font-bold text-xl text-blue-700">
                <a href="/">GDG Blog</a>
            </div>
            <a href="/about">About Us</a>
        </div>
    </div>
</template>
